development:
  adapter: mysql2
  database: myaccount
  pool: 5
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: planeta2014
  timeout: 5000

production:
  adapter: mysql2
  database: myaccount
  pool: 5
  host: localhost
  encoding: utf8
  username: ruby-admin
  password: s3cr3t0
  timeout: 5000
